Adding tests for LDContextBuilder
launchdarkly/php-server-sdk pull request #209
Opened 2024-10-03 16:50 UTC by ActuallyConnor

**Requirements**

- [x] I have added test coverage for new or changed functionality
- [x] I have followed the repository's [pull request submission guidelines](../blob/main/CONTRIBUTING.md#submitting-pull-requests)
- [x] I have validated my changes against all supported platform versions

**Related issues**

N/A

**Describe the solution you've provided**

Improve test coverage and test directly [LDContextBuilder.php](https://github.com/launchdarkly/php-server-sdk/blob/main/src/LaunchDarkly/LDContextBuilder.php)

**Describe alternatives you've considered**
This class was tested indirectly previously but contained logic that would benefit from testing directly.

**Additional context**

N/A

2024-10-03 17:18 UTC, keelerm84 requested changes
Thank you for your interest and in taking the time to contribute!

> This class was tested indirectly previously but contained logic that would benefit from testing directly.

I'm not sure which tests you are referring to. If you look at `LDContextTest.php`, most of the tests interact with the context builder (via `LDContext::builder`). As a result, I think several of the tests in this PR are redundant with what we currently have.

However, there are a couple of tests which I think we did miss. If you want to move those tests into that file, I would be happy to include those contributions. I've tried to note which ones to keep and which to save. 

LMK if you have any questions!

2024-10-03 17:18 UTC, keelerm84 commented on tests/LDContextBuilderTest.php
> +    }
I think all of these are redundant with tests we already have.

2024-10-03 17:18 UTC, keelerm84 commented on tests/LDContextBuilderTest.php
> +     * @dataProvider trySetDataProvider
I will comment on the provider which tests I think are providing new value.

2024-10-03 17:18 UTC, keelerm84 commented on tests/LDContextBuilderTest.php
> +    public function testPrivate(): void
This test is also redundant.

2024-10-03 17:18 UTC, keelerm84 commented on tests/LDContextBuilderTest.php
> +    public function testPrivateEmptyAttributeRefs(): void
We don't have coverage for this exact scenario. I would be okay including this test if you can move it with the others and update to match the testing style in that file.

2024-10-03 17:18 UTC, keelerm84 commented on tests/LDContextBuilderTest.php
> +            ],
These are redundant.

2024-10-03 17:18 UTC, keelerm84 commented on tests/LDContextBuilderTest.php
> +            'attributes name value' => [
We don't have a test checking setting a custom attribute to null. You could probably just fold that into the `testBuilderSetCustomAttributes` test.

2024-10-07 16:49 UTC, ActuallyConnor commented
@keelerm84 I've applied the requested changes to this PR

2024-10-07 19:57 UTC, keelerm84 approved these changes

2024-10-07 19:58 UTC, merged

2024-10-07 19:59 UTC, keelerm84 commented
Thank you for addressing this feedback, and once again, thank you for taking the time to contribute to this project!